# Test configuration for CRISPR screen analysis pipeline

# Sample information
samples:
  - name: "test_sample"
    fastq: "data/fastq/test_sample.fastq.gz"

# sgRNA library file
library:
  file: "data/library/library.txt"
  
# Analysis parameters
params:
  # Quality control
  qc:
    min_quality: 20
    min_length: 18
    
  # Read counting
  counting:
    mismatches: 0
    
  # MAGeCK parameters
  mageck:
    fdr_threshold: 0.25
    norm_method: "median"
    
  # DrugZ parameters
  drugz:
    remove_genes: []
    pseudocount: 5
    min_observations: 1

# Comparisons for differential analysis
comparisons: []

# Output options
output:
  generate_plots: true
  generate_reports: false
